import fs from 'fs';

const file = fs.readFileSync('src/data/foods.js', 'utf8');

const dictionary = {
    'Komkommer': 'Cucumber',
    'Tomaat': 'Tomato',
    'Paprika (Rood)': 'Bell Pepper (Red)',
    'Broccoli – rauw': 'Broccoli - raw',
    'Broccoli – bereid': 'Broccoli - cooked',
    'Sperziebonen – rauw': 'Green beans - raw',
    'Sperziebonen – bereid': 'Green beans - cooked',
    'Spinazie – rauw': 'Spinach - raw',
    'Spinazie – bereid': 'Spinach - cooked',
    'Wortel – rauw': 'Carrot - raw',
    'Wortel – bereid': 'Carrot - cooked',
    'Courgette': 'Zucchini',
    'Aubergine': 'Eggplant',
    'Bloemkool (gekookt)': 'Cauliflower (cooked)',
    'IJsbergsla': 'Iceberg lettuce',
    'Rucola': 'Arugula',
    'Ui (rood)': 'Red onion',
    'Champignons': 'Mushrooms',
    'Zoete aardappel (bereid)': 'Sweet potato (cooked)',
    'Aardappel (gekookt)': 'Potato (cooked)',
    'Pompoen': 'Pumpkin',
    'Doperwten (diepvries)': 'Peas (frozen)',
    'Mais (blik)': 'Corn (canned)',
    'Witlof': 'Chicory',
    'Asperges (groen)': 'Asparagus (green)',
    'Boerenkool (rauw)': 'Kale (raw)',
    'Spruitjes (gekookt)': 'Brussels sprouts (cooked)',
    'Radijs': 'Radish',
    'Prei (gekookt)': 'Leek (cooked)',
    'Selderij (stengel)': 'Celery',
    'Rode biet (gekookt)': 'Beetroot (cooked)',
    'Witkool': 'White cabbage',
    'Snijbonen': 'String beans',
    'Knoflook': 'Garlic',
    'Banaan': 'Banana',
    'Appel (Elstar)': 'Apple (Elstar)',
    'Peer': 'Pear',
    'Blauwe bessen': 'Blueberries',
    'Aardbeien': 'Strawberries',
    'Frambozen': 'Raspberries',
    'Sinaasappel': 'Orange',
    'Mandarijn': 'Mandarin',
    'Druiven (wit)': 'Grapes (white)',
    'Kiwi': 'Kiwi',
    'Mango': 'Mango',
    'Ananas': 'Pineapple',
    'Meloen (Galia)': 'Melon (Galia)',
    'Watermeloen': 'Watermelon',
    'Perzik': 'Peach',
    'Pruim': 'Plum',
    'Avocado': 'Avocado',
    'Citroen': 'Lemon',
    'Kersen': 'Cherries',
    'Grapefruit': 'Grapefruit',
    'Limoen': 'Lime',
    'Nectarine': 'Nectarine',
    'Passievrucht': 'Passion fruit',
    'Granaatappel': 'Pomegranate',
    'Bramen': 'Blackberries',
    'Vijgen (vers)': 'Figs (fresh)',
    'Dadels (gedroogd)': 'Dates (dried)',
    'Rozijnen': 'Raisins',
    'Abrikoos (vers)': 'Apricot (fresh)',
    'Papaya': 'Papaya',
    'Rijst wit – ongekookt': 'White rice - uncooked',
    'Rijst wit – gekookt': 'White rice - cooked',
    'Rijst zilvervlies – ongekookt': 'Brown rice - uncooked',
    'Rijst zilvervlies – gekookt': 'Brown rice - cooked',
    'Pasta wit – ongekookt': 'White pasta - uncooked',
    'Pasta wit – gekookt': 'White pasta - cooked',
    'Pasta volkoren – ongekookt': 'Whole wheat pasta - uncooked',
    'Pasta volkoren – gekookt': 'Whole wheat pasta - cooked',
    'Havermout (onbereid)': 'Oatmeal (raw)',
    'Brood (volkoren)': 'Bread (whole wheat)',
    'Brood (wit)': 'Bread (white)',
    'Beschuit (volkoren)': 'Rusk (whole wheat)',
    'Cracker (volkoren)': 'Cracker (whole wheat)',
    'Couscous (bereid)': 'Couscous (cooked)',
    'Quinoa (bereid)': 'Quinoa (cooked)',
    'Wrap (tortilla)': 'Wrap (tortilla)',
    'Muesli (naturel)': 'Muesli (natural)',
    'Granola': 'Granola',
    'Rijstwafel': 'Rice cake',
    'Boekweit': 'Buckwheat',
    'Bulgur (bereid)': 'Bulgur (cooked)',
    'Parelgort (bereid)': 'Pearl barley (cooked)',
    'Mie / Noedels (ei, gekookt)': 'Egg noodles (cooked)',
    'Udon noedels': 'Udon noodles',
    'Soba noedels': 'Soba noodles',
    'Speltbrood': 'Spelt bread',
    'Roggebrood': 'Rye bread',
    'Croissant': 'Croissant',
    'Stokbrood (wit)': 'Baguette (white)',
    'Wrap (wortel)': 'Wrap (carrot)',
    'Wrap (volkoren)': 'Wrap (whole wheat)',
    'Kipfilet – rauw': 'Chicken breast - raw',
    'Kipfilet – bereid': 'Chicken breast - cooked',
    'Rundergehakt mager – rauw': 'Lean minced beef - raw',
    'Rundergehakt mager – bereid': 'Lean minced beef - cooked',
    'Biefstuk – rauw': 'Steak - raw',
    'Biefstuk – bereid': 'Steak - cooked',
    'Zalm – rauw': 'Salmon - raw',
    'Zalm – bereid': 'Salmon - cooked',
    'Tonijn (blik, water)': 'Tuna (canned, water)',
    'Witvis (kabeljauw / koolvis)': 'White fish (cod / pollock)',
    'Gerookte zalm': 'Smoked salmon',
    'Ei (gekookt)': 'Egg (boiled)',
    'Ei (scrambled)': 'Egg (scrambled)',
    'Ei (gebakken)': 'Egg (fried)',
    'Omelet (naturel)': 'Omelet (plain)',
    'Eiwit (vloeibaar)': 'Egg whites (liquid)',
    'Tofu': 'Tofu',
    'Tempeh': 'Tempeh',
    'Linzen (gekookt)': 'Lentils (cooked)',
    'Kikkererwten (gekookt)': 'Chickpeas (cooked)',
    'Vegetarisch gehakt': 'Vegetarian minced meat',
    'Kalkoenfilet (vleeswaren)': 'Turkey breast (cold cuts)',
    'Ham (achterham)': 'Ham',
    'Whey Proteine poeder': 'Whey Protein powder',
    'Vegan Proteine poeder': 'Vegan Protein powder',
    'Hüttenkäse': 'Cottage cheese',
    'Garnalen (gekookt)': 'Shrimp (cooked)',
    'Makreel (gerookt)': 'Mackerel (smoked)',
    'Sardines (blik)': 'Sardines (canned)',
    'Varkenshaas': 'Pork tenderloin',
    'Rosbief (vleeswaren)': 'Roast beef (cold cuts)',
    'Kipfilet (vleeswaren)': 'Chicken breast (cold cuts)',
    'Seitan': 'Seitan',
    'Edamame (bonen)': 'Edamame (beans)',
    'Bruine bonen (blik)': 'Brown beans (canned)',
    'Kidneybonen (blik)': 'Kidney beans (canned)',
    'Zwarte bonen': 'Black beans',
    'Cannellini bonen': 'Cannellini beans',
    'Falafel (balletjes)': 'Falafel',
    'Vega burger': 'Veggie burger',
    'Valess burger': 'Valess burger',
    'Haring (zout)': 'Herring (salted)',
    'Paling (gerookt)': 'Eel (smoked)',
    'Forel (gerookt)': 'Trout (smoked)',
    'Mosselen (gekookt)': 'Mussels (cooked)',
    'Oesters': 'Oysters',
    'Kippendij zonder vel – rauw': 'Chicken thigh (skinless) - raw',
    'Kippendij zonder vel – bereid': 'Chicken thigh (skinless) - cooked',
    'Kippendij met vel – rauw': 'Chicken thigh (with skin) - raw',
    'Kippendij met vel – bereid': 'Chicken thigh (with skin) - cooked',
    'Rundergehakt normaal – rauw': 'Minced beef (regular) - raw',
    'Rundergehakt normaal – bereid': 'Minced beef (regular) - cooked',
    'Half-om-half gehakt – rauw': 'Mixed minced meat - raw',
    'Half-om-half gehakt – bereid': 'Mixed minced meat - cooked',
    'Runderstoofvlees – rauw': 'Beef stew meat - raw',
    'Runderstoofvlees – bereid': 'Beef stew meat - cooked',
    'Varkensfilet – rauw': 'Pork fillet - raw',
    'Varkensfilet – bereid': 'Pork fillet - cooked',
    'Speklap – rauw': 'Pork belly - raw',
    'Speklap – bereid': 'Pork belly - cooked',
    'Tonijn vers – rauw': 'Fresh tuna - raw',
    'Tonijn vers – bereid': 'Fresh tuna - cooked',
    'Magere kwark': 'Fat-free quark',
    'Griekse yoghurt 0% vet': 'Greek yogurt 0% fat',
    'Griekse yoghurt 10% vet': 'Greek yogurt 10% fat',
    'Volle yoghurt': 'Whole milk yogurt',
    'Magere melk': 'Skim milk',
    'Halfvolle melk': 'Semi-skimmed milk',
    'Amandelmelk (ongezoet)': 'Almond milk (unsweetened)',
    'Sojamelk (ongezoet)': 'Soy milk (unsweetened)',
    'Havermelk': 'Oat milk',
    'Kaas (Gouda 48+)': 'Cheese (Gouda 48+)',
    'Kaas (30+)': 'Cheese (30+)',
    'Mozzarella': 'Mozzarella',
    'Feta': 'Feta',
    'Parmezaanse kaas': 'Parmesan cheese',
    'Karnemelk': 'Buttermilk',
    'Skyr (naturel)': 'Skyr (plain)',
    'Volle melk': 'Whole milk',
    'Geitenkaas (zacht)': 'Goat cheese (soft)',
    'Brie': 'Brie',
    'Camembert': 'Camembert',
    'Ricotta': 'Ricotta',
    'Mascarpone': 'Mascarpone',
    'Goudse kaas (30+)': 'Gouda cheese (30+)',
    'Cheddar': 'Cheddar',
    'Roomkaas': 'Cream cheese',
    'Kokosyoghurt (naturel)': 'Coconut yogurt (plain)',
    'Slagroom (ongeklopt)': 'Heavy cream',
    'IJs (vanille)': 'Ice cream (vanilla)',
    'Koffiemelk': 'Coffee milk',
    'Melk (chocolade)': 'Chocolate milk',
    'Olijfolie': 'Olive oil',
    'Roomboter (ongezouten)': 'Butter (unsalted)',
    'Kokosolie': 'Coconut oil',
    'Pindakaas (100%)': 'Peanut butter (100%)',
    'Amandelen (ongebrand)': 'Almonds (raw)',
    'Walnoten': 'Walnuts',
    'Cashewnoten': 'Cashews',
    "Pinda\'s": 'Peanuts',
    'Lijnzaad': 'Flaxseed',
    'Chiazaad': 'Chia seeds',
    'Zonnebloempitten': 'Sunflower seeds',
    'Mayonaise': 'Mayonnaise',
    'Pesto (groen)': 'Pesto (green)',
    'Hummus (naturel)': 'Hummus (plain)',
    'Hazelnoten': 'Hazelnuts',
    'Pacannoten': 'Pecans',
    'Pistachenoten (ongezouten)': 'Pistachios (unsalted)',
    'Macadamia noten': 'Macadamia nuts',
    'Pompoenpitten': 'Pumpkin seeds',
    'Sesamzaad': 'Sesame seeds',
    'Zonnebloemolie': 'Sunflower oil',
    'Halvarine': 'Low-fat margarine',
    'Aioli': 'Aioli',
    'Guacamole': 'Guacamole',
    'Tahin (sesampasta)': 'Tahini',
    'Pure Chocolade (85%)': 'Dark Chocolate (85%)',
    'Melkchocolade': 'Milk chocolate',
    'Popcorn (zout)': 'Popcorn (salted)',
    'Chips (naturel)': 'Potato chips (plain)',
    'Honing': 'Honey',
    'Jam (aardbei)': 'Jam (strawberry)',
    'Hagelslag (puur)': 'Chocolate sprinkles (dark)',
    'Ontbijtkoek': 'Gingerbread',
    'Speculaasje': 'Spiced biscuit',
    'Eierkoek': 'Egg cake',
    'Mueslireep': 'Muesli bar',
    'Digestive biscuit': 'Digestive biscuit',
    'Stroopwafel': 'Stroopwafel',
    'Drop (zout)': 'Licorice (salty)',
    'Winegums': 'Wine gums',
    'Lange vingers': 'Ladyfingers',
    'Bokkenpootje': 'Bokkenpootje',
    'Tompouce': 'Tompouce',
    'Gevulde koek': 'Almond paste cookie',
    'Bitterbal': 'Bitterbal',
    'Frikandel': 'Frikandel',
    'Kroket': 'Croquette',
    'Kaassoufflé': 'Cheese soufflé',
    'Agavesiroop': 'Agave syrup',
    'Esdoornsiroop (Maple)': 'Maple syrup',
    'Basterdsuiker': 'Brown sugar',
    'Ketchup': 'Ketchup',
    'Curry gewürz': 'Curry ketchup',
    'Satésaus (bereid)': 'Peanut sauce (prepared)',
    'Mosterd': 'Mustard',
    'Ketjap Manis': 'Sweet soy sauce',
    'Sojavaus (zout)': 'Soy sauce (salty)',
    'Appelstroop': 'Apple butter',
    'Hagelslag (melk)': 'Chocolate sprinkles (milk)',
    'Vla (vanille)': 'Custard (vanilla)',
    'Chocomousse': 'Chocolate mousse',
    'Gelatine pudding': 'Jell-O',
    'Tiramisu': 'Tiramisu',
    'Cheesecake': 'Cheesecake',
    'Brownie': 'Brownie',
    'Muffin (bosbes)': 'Muffin (blueberry)',
    'Donut (suiker)': 'Donut (sugar)',
    'Pannenkoek (naturel)': 'Pancake (plain)',
    'Pofrertjes': 'Poffertjes',
    'Wafel (Luikse)': 'Waffle (Liege)'
};

let modifiedContent = file;
for (const [nl, en] of Object.entries(dictionary)) {
    const searchString = `name_nl: '${nl}'`;
    const replaceString = `name_nl: '${nl}', name_en: '${en.replace(/'/g, "\\'")}'`;
    modifiedContent = modifiedContent.replace(searchString, replaceString);
}

fs.writeFileSync('src/data/foods.js', modifiedContent, 'utf8');
console.log('Done mapping english translations.');
